format = """
$directory\
$git_branch\
$git_status\
$fill\
$lua\
$dart\
$html\
$css\
$javascript\
$python\
$jobs\
$cmd_duration\
$line_break\
$character"""

palette = 'myColors'


[character]
success_symbol = '[❯](bold green) '
error_symbol = '[✗](bold red) '

[directory]
truncation_symbol= '.../'

[dart]
style= 'dart_blue'
format = '[$symbol($version )]($style)'
symbol = ''


[fill]
symbol = ' '

[git_branch]
style= 'orange'
symbol = ''
format = 'on [$symbol $branch(:$remote_branch)]($style)'

[jobs]
symbol = '⚙'
format = '[$number$symbol]($style) '
style= 'red'

[lua]
symbol = ''
format = '[$symbol ($version )]($style)'
[palettes.myColors]
orange = '#FFA500'
dart_blue = '#0175C2'

